<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>io.vertigo</groupId>
		<artifactId>vertigo-modules</artifactId>
		<version>4.4.0-SNAPSHOT</version>
	</parent>

	<artifactId>vertigo-geo</artifactId>
	<packaging>jar</packaging>
	<name>vertigo-geo</name>

	<dependencyManagement>
		<dependencies>
			<!-- Import ES7 versions from vertigo-lts-libs -->
			<dependency>
				<groupId>io.vertigo</groupId>
				<artifactId>vertigo-datafactory-plugin-elasticsearch_7_17</artifactId>
				<version>${vertigo.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>io.vertigo</groupId>
				<artifactId>vertigo-connectors</artifactId>
				<version>${vertigo.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>io.vertigo</groupId>
			<artifactId>vertigo-datamodel</artifactId>
			<version>${vertigo.version}</version>
		</dependency>
		<!-- Search -->
		<dependency>
			<groupId>org.elasticsearch</groupId>
			<artifactId>elasticsearch</artifactId>
			<optional>true</optional>
			<exclusions>
				<exclusion>
					<groupId>org.apache.logging.log4j</groupId>
					<artifactId>log4j-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.elasticsearch.client</groupId>
			<artifactId>elasticsearch-rest-high-level-client</artifactId>
			<optional>true</optional> <!-- RestHighLevelElasticSearchConnector -->
		</dependency>
		<!-- ES7 connector -->
		<dependency>
			<groupId>io.vertigo</groupId>
			<artifactId>vertigo-elasticsearch_7_17-connector</artifactId>
			<version>${vertigo.version}</version>
			<optional>true</optional> <!-- ESGeoSearchPlugin -->
		</dependency>
	</dependencies>
</project>
