package io.vertigo.planning.agenda.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.DataObject;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class AgendaDisplay implements DataObject {
	private static final long serialVersionUID = 1L;

	private Long ageId;
	private String name;
	private String overridedName;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Id'.
	 * @return Long ageId <b>Obligatoire</b>
	 */
	@Field(smartType = "STyPId", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Id")
	public Long getAgeId() {
		return ageId;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Id'.
	 * @param ageId Long <b>Obligatoire</b>
	 */
	public void setAgeId(final Long ageId) {
		this.ageId = ageId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Name'.
	 * @return String name <b>Obligatoire</b>
	 */
	@Field(smartType = "STyPLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Name")
	public String getName() {
		return name;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Name'.
	 * @param name String <b>Obligatoire</b>
	 */
	public void setName(final String name) {
		this.name = name;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Name'.
	 * @return String overridedName
	 */
	@Field(smartType = "STyPLabel", label = "Name")
	public String getOverridedName() {
		return overridedName;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Name'.
	 * @param overridedName String
	 */
	public void setOverridedName(final String overridedName) {
		this.overridedName = overridedName;
	}
	
	/**
	 * Champ : COMPUTED.
	 * Récupère la valeur de la propriété calculée 'Nom agenda'.
	 * @return String displayName
	 */
	@Field(smartType = "STyPLabel", type = "COMPUTED", persistent = false, label = "Nom agenda")
	@io.vertigo.datamodel.data.stereotype.DisplayField
	public String getDisplayName() {
		if (overridedName != null) {
			return overridedName;
		}
		return name;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
