/*
 * vertigo - application development platform
 *
 * Copyright (C) 2013-2026, Vertigo.io, team@vertigo.io
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.vertigo.planning.agenda.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.DataObject;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class DuplicationJourForm implements DataObject {
	private static final long serialVersionUID = 1L;

	private java.time.LocalDate dateLocaleFrom;
	private java.util.List<java.time.LocalDate> dateLocaleTo = new java.util.ArrayList<>();
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Date à dupliquer'.
	 * @return LocalDate dateLocaleFrom <b>Obligatoire</b>
	 */
	@Field(smartType = "STyPLocalDate", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Date à dupliquer")
	public java.time.LocalDate getDateLocaleFrom() {
		return dateLocaleFrom;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Date à dupliquer'.
	 * @param dateLocaleFrom LocalDate <b>Obligatoire</b>
	 */
	public void setDateLocaleFrom(final java.time.LocalDate dateLocaleFrom) {
		this.dateLocaleFrom = dateLocaleFrom;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Jours cible'.
	 * @return List de LocalDate dateLocaleTo
	 */
	@Field(smartType = "STyPLocalDate", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Jours cible")
	public java.util.List<java.time.LocalDate> getDateLocaleTo() {
		return dateLocaleTo;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Jours cible'.
	 * @param dateLocaleTo List de LocalDate
	 */
	public void setDateLocaleTo(final java.util.List<java.time.LocalDate> dateLocaleTo) {
		io.vertigo.core.lang.Assertion.check().isNotNull(dateLocaleTo);
		//---
		this.dateLocaleTo = dateLocaleTo;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
