package io.vertigo.planning.agenda.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.DataObject;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class DuplicationJourForm implements DataObject {
	private static final long serialVersionUID = 1L;

	private java.time.LocalDate dateLocaleFrom;
	private java.util.List<java.time.LocalDate> dateLocaleTo = new java.util.ArrayList<>();
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Date à dupliquer'.
	 * @return LocalDate dateLocaleFrom <b>Obligatoire</b>
	 */
	@Field(smartType = "STyPLocalDate", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Date à dupliquer")
	public java.time.LocalDate getDateLocaleFrom() {
		return dateLocaleFrom;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Date à dupliquer'.
	 * @param dateLocaleFrom LocalDate <b>Obligatoire</b>
	 */
	public void setDateLocaleFrom(final java.time.LocalDate dateLocaleFrom) {
		this.dateLocaleFrom = dateLocaleFrom;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Jours cible'.
	 * @return List de LocalDate dateLocaleTo
	 */
	@Field(smartType = "STyPLocalDate", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Jours cible")
	public java.util.List<java.time.LocalDate> getDateLocaleTo() {
		return dateLocaleTo;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Jours cible'.
	 * @param dateLocaleTo List de LocalDate
	 */
	public void setDateLocaleTo(final java.util.List<java.time.LocalDate> dateLocaleTo) {
		io.vertigo.core.lang.Assertion.check().isNotNull(dateLocaleTo);
		//---
		this.dateLocaleTo = dateLocaleTo;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
