package io.vertigo.planning.agenda.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.DataObject;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class InfoCalendrierDisplay implements DataObject {
	private static final long serialVersionUID = 1L;

	private java.time.LocalDate date;
	private String libelle;
	private String infobulle;
	private String htmlClass;
	private String htmlStyle;
	private Boolean siFerme;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Date de l'information'.
	 * @return LocalDate date <b>Obligatoire</b>
	 */
	@Field(smartType = "STyPLocalDate", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Date de l'information")
	public java.time.LocalDate getDate() {
		return date;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Date de l'information'.
	 * @param date LocalDate <b>Obligatoire</b>
	 */
	public void setDate(final java.time.LocalDate date) {
		this.date = date;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Libellé'.
	 * @return String libelle <b>Obligatoire</b>
	 */
	@Field(smartType = "STyPLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Libellé")
	public String getLibelle() {
		return libelle;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Libellé'.
	 * @param libelle String <b>Obligatoire</b>
	 */
	public void setLibelle(final String libelle) {
		this.libelle = libelle;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Infobulle'.
	 * @return String infobulle
	 */
	@Field(smartType = "STyPLabel", label = "Infobulle")
	public String getInfobulle() {
		return infobulle;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Infobulle'.
	 * @param infobulle String
	 */
	public void setInfobulle(final String infobulle) {
		this.infobulle = infobulle;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Classe pour l'affichage dans l'agenda'.
	 * @return String htmlClass
	 */
	@Field(smartType = "STyPLabel", label = "Classe pour l'affichage dans l'agenda")
	public String getHtmlClass() {
		return htmlClass;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Classe pour l'affichage dans l'agenda'.
	 * @param htmlClass String
	 */
	public void setHtmlClass(final String htmlClass) {
		this.htmlClass = htmlClass;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Style pour l'affichage dans l'agenda'.
	 * @return String htmlStyle
	 */
	@Field(smartType = "STyPLabel", label = "Style pour l'affichage dans l'agenda")
	public String getHtmlStyle() {
		return htmlStyle;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Style pour l'affichage dans l'agenda'.
	 * @param htmlStyle String
	 */
	public void setHtmlStyle(final String htmlStyle) {
		this.htmlStyle = htmlStyle;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Si le jour est considéré comme fermé, on ne dupliquera pas les plages horaires'.
	 * @return Boolean siFerme <b>Obligatoire</b>
	 */
	@Field(smartType = "STyPBooleen", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Si le jour est considéré comme fermé, on ne dupliquera pas les plages horaires")
	public Boolean getSiFerme() {
		return siFerme;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Si le jour est considéré comme fermé, on ne dupliquera pas les plages horaires'.
	 * @param siFerme Boolean <b>Obligatoire</b>
	 */
	public void setSiFerme(final Boolean siFerme) {
		this.siFerme = siFerme;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
