package io.vertigo.easyforms.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.Data;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class EasyFormsFieldUi implements Data {
	private static final long serialVersionUID = 1L;

	private String fieldCode;
	private String fieldType;
	private String fieldTypeLabel;
	private String label;
	private String tooltip;
	private Boolean isDefault;
	private Boolean isMandatory;
	private io.vertigo.easyforms.easyformsrunner.model.template.EasyFormsData parameters;
	private io.vertigo.easyforms.easyformsrunner.model.ui.EasyFormsTemplateFieldValidatorUiList fieldValidators;
	private java.util.List<String> fieldValidatorSelection = new java.util.ArrayList<>();
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Field code'.
	 * @return String fieldCode
	 */
	@Field(smartType = "STyEfCode", label = "Field code")
	public String getFieldCode() {
		return fieldCode;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Field code'.
	 * @param fieldCode String
	 */
	public void setFieldCode(final String fieldCode) {
		this.fieldCode = fieldCode;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Field type'.
	 * @return String fieldType
	 */
	@Field(smartType = "STyEfLabel", label = "Field type")
	public String getFieldType() {
		return fieldType;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Field type'.
	 * @param fieldType String
	 */
	public void setFieldType(final String fieldType) {
		this.fieldType = fieldType;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Field type'.
	 * @return String fieldTypeLabel
	 */
	@Field(smartType = "STyEfLabel", label = "Field type")
	public String getFieldTypeLabel() {
		return fieldTypeLabel;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Field type'.
	 * @param fieldTypeLabel String
	 */
	public void setFieldTypeLabel(final String fieldTypeLabel) {
		this.fieldTypeLabel = fieldTypeLabel;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Label'.
	 * @return String label
	 */
	@Field(smartType = "STyEfLabel", label = "Label")
	public String getLabel() {
		return label;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Label'.
	 * @param label String
	 */
	public void setLabel(final String label) {
		this.label = label;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Tooltip'.
	 * @return String tooltip
	 */
	@Field(smartType = "STyEfLabel", label = "Tooltip")
	public String getTooltip() {
		return tooltip;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Tooltip'.
	 * @param tooltip String
	 */
	public void setTooltip(final String tooltip) {
		this.tooltip = tooltip;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'System field'.
	 * @return Boolean isDefault
	 */
	@Field(smartType = "STyEfBooleen", label = "System field")
	public Boolean getIsDefault() {
		return isDefault;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'System field'.
	 * @param isDefault Boolean
	 */
	public void setIsDefault(final Boolean isDefault) {
		this.isDefault = isDefault;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Mandatory'.
	 * @return Boolean isMandatory
	 */
	@Field(smartType = "STyEfBooleen", label = "Mandatory")
	public Boolean getIsMandatory() {
		return isMandatory;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Mandatory'.
	 * @param isMandatory Boolean
	 */
	public void setIsMandatory(final Boolean isMandatory) {
		this.isMandatory = isMandatory;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Parameters'.
	 * @return EasyFormsData parameters
	 */
	@Field(smartType = "STyEfFormData", label = "Parameters")
	public io.vertigo.easyforms.easyformsrunner.model.template.EasyFormsData getParameters() {
		return parameters;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Parameters'.
	 * @param parameters EasyFormsData
	 */
	public void setParameters(final io.vertigo.easyforms.easyformsrunner.model.template.EasyFormsData parameters) {
		this.parameters = parameters;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Validators'.
	 * @return EasyFormsTemplateFieldValidatorUiList fieldValidators
	 */
	@Field(smartType = "STyEfFieldValidatorUiList", label = "Validators")
	public io.vertigo.easyforms.easyformsrunner.model.ui.EasyFormsTemplateFieldValidatorUiList getFieldValidators() {
		return fieldValidators;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Validators'.
	 * @param fieldValidators EasyFormsTemplateFieldValidatorUiList
	 */
	public void setFieldValidators(final io.vertigo.easyforms.easyformsrunner.model.ui.EasyFormsTemplateFieldValidatorUiList fieldValidators) {
		this.fieldValidators = fieldValidators;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Validators'.
	 * @return List de String fieldValidatorSelection
	 */
	@Field(smartType = "STyEfLabel", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Validators")
	public java.util.List<String> getFieldValidatorSelection() {
		return fieldValidatorSelection;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Validators'.
	 * @param fieldValidatorSelection List de String
	 */
	public void setFieldValidatorSelection(final java.util.List<String> fieldValidatorSelection) {
		io.vertigo.core.lang.Assertion.check().isNotNull(fieldValidatorSelection);
		//---
		this.fieldValidatorSelection = fieldValidatorSelection;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataUtil.toString(this);
	}
}
