package io.vertigo.easyforms.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.DataObject;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class EasyFormsSectionUi implements DataObject {
	private static final long serialVersionUID = 1L;

	private String fieldCode;
	private String title;
	private String condition;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Code'.
	 * @return String fieldCode <b>Obligatoire</b>
	 */
	@Field(smartType = "STyEfCode", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Code")
	public String getFieldCode() {
		return fieldCode;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Code'.
	 * @param fieldCode String <b>Obligatoire</b>
	 */
	public void setFieldCode(final String fieldCode) {
		this.fieldCode = fieldCode;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Title'.
	 * @return String title <b>Obligatoire</b>
	 */
	@Field(smartType = "STyEfLabel", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Title")
	public String getTitle() {
		return title;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Title'.
	 * @param title String <b>Obligatoire</b>
	 */
	public void setTitle(final String title) {
		this.title = title;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Display condition'.
	 * @return String condition
	 */
	@Field(smartType = "STyEfLabel", label = "Display condition")
	public String getCondition() {
		return condition;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Display condition'.
	 * @param condition String
	 */
	public void setCondition(final String condition) {
		this.condition = condition;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
