package io.vertigo.easyforms.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class EasyFormsFieldConstraintUi implements DtObject {
	private static final long serialVersionUID = 1L;

	private String code;
	private String label;
	private String description;
	private java.util.List<String> fieldTypes = new java.util.ArrayList<>();
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Constraint'.
	 * @return String code
	 */
	@Field(smartType = "STyEfCode", label = "Constraint")
	@io.vertigo.datamodel.structure.stereotype.SortField
	public String getCode() {
		return code;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Constraint'.
	 * @param code String
	 */
	public void setCode(final String code) {
		this.code = code;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Constraint'.
	 * @return String label
	 */
	@Field(smartType = "STyEfLabel", label = "Constraint")
	@io.vertigo.datamodel.structure.stereotype.DisplayField
	public String getLabel() {
		return label;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Constraint'.
	 * @param label String
	 */
	public void setLabel(final String label) {
		this.label = label;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Description'.
	 * @return String description
	 */
	@Field(smartType = "STyEfText", label = "Description")
	public String getDescription() {
		return description;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Description'.
	 * @param description String
	 */
	public void setDescription(final String description) {
		this.description = description;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Attached to fields'.
	 * @return List de String fieldTypes
	 */
	@Field(smartType = "STyEfText", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Attached to fields")
	public java.util.List<String> getFieldTypes() {
		return fieldTypes;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Attached to fields'.
	 * @param fieldTypes List de String
	 */
	public void setFieldTypes(final java.util.List<String> fieldTypes) {
		io.vertigo.core.lang.Assertion.check().isNotNull(fieldTypes);
		//---
		this.fieldTypes = fieldTypes;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
