package io.vertigo.easyforms.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.Entity;
import io.vertigo.datamodel.data.model.UID;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class EasyForm implements Entity {
	private static final long serialVersionUID = 1L;

	private Long efoId;
	private io.vertigo.easyforms.easyformsrunner.model.EasyFormsTemplate template;

	/** {@inheritDoc} */
	@Override
	public UID<EasyForm> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Id'.
	 * @return Long efoId <b>Obligatoire</b>
	 */
	@Field(smartType = "STyEfId", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Id")
	public Long getEfoId() {
		return efoId;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Id'.
	 * @param efoId Long <b>Obligatoire</b>
	 */
	public void setEfoId(final Long efoId) {
		this.efoId = efoId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Template'.
	 * @return EasyFormsTemplate template
	 */
	@Field(smartType = "STyEfFormTemplate", label = "Template")
	public io.vertigo.easyforms.easyformsrunner.model.EasyFormsTemplate getTemplate() {
		return template;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Template'.
	 * @param template EasyFormsTemplate
	 */
	public void setTemplate(final io.vertigo.easyforms.easyformsrunner.model.EasyFormsTemplate template) {
		this.template = template;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
