package io.vertigo.easyforms.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.DataObject;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class EasyFormsItemUi implements DataObject {
	private static final long serialVersionUID = 1L;

	private String type;
	private String fieldCode;
	private String fieldType;
	private String tooltip;
	private Boolean isDefault;
	private Boolean isMandatory;
	private io.vertigo.easyforms.runner.model.template.EasyFormsData parameters;
	private java.util.List<String> fieldValidatorSelection = new java.util.ArrayList<>();
	private String condition;
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Item type'.
	 * @return String type
	 */
	@Field(smartType = "STyEfCode", label = "Item type")
	public String getType() {
		return type;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Item type'.
	 * @param type String
	 */
	public void setType(final String type) {
		this.type = type;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Field code'.
	 * @return String fieldCode
	 */
	@Field(smartType = "STyEfCode", label = "Field code")
	public String getFieldCode() {
		return fieldCode;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Field code'.
	 * @param fieldCode String
	 */
	public void setFieldCode(final String fieldCode) {
		this.fieldCode = fieldCode;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Field type'.
	 * @return String fieldType
	 */
	@Field(smartType = "STyEfLabel", label = "Field type")
	public String getFieldType() {
		return fieldType;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Field type'.
	 * @param fieldType String
	 */
	public void setFieldType(final String fieldType) {
		this.fieldType = fieldType;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Tooltip'.
	 * @return String tooltip
	 */
	@Field(smartType = "STyEfLabel", label = "Tooltip")
	public String getTooltip() {
		return tooltip;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Tooltip'.
	 * @param tooltip String
	 */
	public void setTooltip(final String tooltip) {
		this.tooltip = tooltip;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'System field'.
	 * @return Boolean isDefault
	 */
	@Field(smartType = "STyEfBooleen", label = "System field")
	public Boolean getIsDefault() {
		return isDefault;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'System field'.
	 * @param isDefault Boolean
	 */
	public void setIsDefault(final Boolean isDefault) {
		this.isDefault = isDefault;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Mandatory'.
	 * @return Boolean isMandatory
	 */
	@Field(smartType = "STyEfBooleen", label = "Mandatory")
	public Boolean getIsMandatory() {
		return isMandatory;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Mandatory'.
	 * @param isMandatory Boolean
	 */
	public void setIsMandatory(final Boolean isMandatory) {
		this.isMandatory = isMandatory;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Parameters'.
	 * @return EasyFormsData parameters
	 */
	@Field(smartType = "STyEfFormData", label = "Parameters")
	public io.vertigo.easyforms.runner.model.template.EasyFormsData getParameters() {
		return parameters;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Parameters'.
	 * @param parameters EasyFormsData
	 */
	public void setParameters(final io.vertigo.easyforms.runner.model.template.EasyFormsData parameters) {
		this.parameters = parameters;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Validators'.
	 * @return List de String fieldValidatorSelection
	 */
	@Field(smartType = "STyEfLabel", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Validators")
	public java.util.List<String> getFieldValidatorSelection() {
		return fieldValidatorSelection;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Validators'.
	 * @param fieldValidatorSelection List de String
	 */
	public void setFieldValidatorSelection(final java.util.List<String> fieldValidatorSelection) {
		io.vertigo.core.lang.Assertion.check().isNotNull(fieldValidatorSelection);
		//---
		this.fieldValidatorSelection = fieldValidatorSelection;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Display condition'.
	 * @return String condition
	 */
	@Field(smartType = "STyEfLabel", label = "Display condition")
	public String getCondition() {
		return condition;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Display condition'.
	 * @param condition String
	 */
	public void setCondition(final String condition) {
		this.condition = condition;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
