package io.vertigo.easyforms.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.structure.model.DtObject;
import io.vertigo.datamodel.structure.stereotype.Field;
import io.vertigo.datamodel.structure.util.DtObjectUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class EasyFormsFieldUi implements DtObject {
	private static final long serialVersionUID = 1L;

	private String fieldCode;
	private String fieldType;
	private String fieldTypeLabel;
	private String label;
	private String tooltip;
	private Boolean isDefault;
	private Boolean isMandatory;
	private java.util.List<String> fieldConstraints = new java.util.ArrayList<>();
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Field code'.
	 * @return String fieldCode
	 */
	@Field(smartType = "STyEfCode", label = "Field code")
	public String getFieldCode() {
		return fieldCode;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Field code'.
	 * @param fieldCode String
	 */
	public void setFieldCode(final String fieldCode) {
		this.fieldCode = fieldCode;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Field type'.
	 * @return String fieldType
	 */
	@Field(smartType = "STyEfLabel", label = "Field type")
	public String getFieldType() {
		return fieldType;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Field type'.
	 * @param fieldType String
	 */
	public void setFieldType(final String fieldType) {
		this.fieldType = fieldType;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Field type'.
	 * @return String fieldTypeLabel
	 */
	@Field(smartType = "STyEfLabel", label = "Field type")
	public String getFieldTypeLabel() {
		return fieldTypeLabel;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Field type'.
	 * @param fieldTypeLabel String
	 */
	public void setFieldTypeLabel(final String fieldTypeLabel) {
		this.fieldTypeLabel = fieldTypeLabel;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Label'.
	 * @return String label
	 */
	@Field(smartType = "STyEfLabel", label = "Label")
	public String getLabel() {
		return label;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Label'.
	 * @param label String
	 */
	public void setLabel(final String label) {
		this.label = label;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Tooltip'.
	 * @return String tooltip
	 */
	@Field(smartType = "STyEfLabel", label = "Tooltip")
	public String getTooltip() {
		return tooltip;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Tooltip'.
	 * @param tooltip String
	 */
	public void setTooltip(final String tooltip) {
		this.tooltip = tooltip;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'System field'.
	 * @return Boolean isDefault
	 */
	@Field(smartType = "STyEfBooleen", label = "System field")
	public Boolean getIsDefault() {
		return isDefault;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'System field'.
	 * @param isDefault Boolean
	 */
	public void setIsDefault(final Boolean isDefault) {
		this.isDefault = isDefault;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Mandatory field'.
	 * @return Boolean isMandatory
	 */
	@Field(smartType = "STyEfBooleen", label = "Mandatory field")
	public Boolean getIsMandatory() {
		return isMandatory;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Mandatory field'.
	 * @param isMandatory Boolean
	 */
	public void setIsMandatory(final Boolean isMandatory) {
		this.isMandatory = isMandatory;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Constraints'.
	 * @return List de String fieldConstraints
	 */
	@Field(smartType = "STyEfText", cardinality = io.vertigo.core.lang.Cardinality.MANY, label = "Constraints")
	public java.util.List<String> getFieldConstraints() {
		return fieldConstraints;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Constraints'.
	 * @param fieldConstraints List de String
	 */
	public void setFieldConstraints(final java.util.List<String> fieldConstraints) {
		io.vertigo.core.lang.Assertion.check().isNotNull(fieldConstraints);
		//---
		this.fieldConstraints = fieldConstraints;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DtObjectUtil.toString(this);
	}
}
