/*
 * vertigo - application development platform
 *
 * Copyright (C) 2013-2024, Vertigo.io, team@vertigo.io
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.vertigo.easyforms.domain;

import io.vertigo.core.lang.Generated;
import io.vertigo.datamodel.data.model.Entity;
import io.vertigo.datamodel.data.model.UID;
import io.vertigo.datamodel.data.stereotype.Field;
import io.vertigo.datamodel.data.util.DataModelUtil;

/**
 * This class is automatically generated.
 * DO NOT EDIT THIS FILE DIRECTLY.
 */
@Generated
public final class EasyForm implements Entity {
	private static final long serialVersionUID = 1L;

	private Long efoId;
	private io.vertigo.easyforms.runner.model.template.EasyFormsTemplate template;

	/** {@inheritDoc} */
	@Override
	public UID<EasyForm> getUID() {
		return UID.of(this);
	}
	
	/**
	 * Champ : ID.
	 * Récupère la valeur de la propriété 'Id'.
	 * @return Long efoId <b>Obligatoire</b>
	 */
	@Field(smartType = "STyEfId", type = "ID", cardinality = io.vertigo.core.lang.Cardinality.ONE, label = "Id")
	public Long getEfoId() {
		return efoId;
	}

	/**
	 * Champ : ID.
	 * Définit la valeur de la propriété 'Id'.
	 * @param efoId Long <b>Obligatoire</b>
	 */
	public void setEfoId(final Long efoId) {
		this.efoId = efoId;
	}
	
	/**
	 * Champ : DATA.
	 * Récupère la valeur de la propriété 'Template'.
	 * @return EasyFormsTemplate template
	 */
	@Field(smartType = "STyEfFormTemplate", label = "Template")
	public io.vertigo.easyforms.runner.model.template.EasyFormsTemplate getTemplate() {
		return template;
	}

	/**
	 * Champ : DATA.
	 * Définit la valeur de la propriété 'Template'.
	 * @param template EasyFormsTemplate
	 */
	public void setTemplate(final io.vertigo.easyforms.runner.model.template.EasyFormsTemplate template) {
		this.template = template;
	}
	
	/** {@inheritDoc} */
	@Override
	public String toString() {
		return DataModelUtil.toString(this);
	}
}
